/**
 * Seed data for Local Fallback Mode & Initial Database Population
 * Realistic community issues with coordinates, before/after evidence, and status progression.
 */

export const INITIAL_PROFILES = [
  {
    id: 'usr_admin_001',
    user_id: 'usr_admin_001',
    name: 'Ward Administrator (CEP Officer)',
    email: 'admin@communityconnect.app',
    role: 'admin',
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'usr_resident_001',
    user_id: 'usr_resident_001',
    name: 'Aarav Sharma (Resident)',
    email: 'resident@communityconnect.app',
    role: 'resident',
    created_at: '2026-08-15T10:30:00Z',
  },
  {
    id: 'usr_resident_002',
    user_id: 'usr_resident_002',
    name: 'Priya Patel (Community Volunteer)',
    email: 'priya.patel@communityconnect.app',
    role: 'resident',
    created_at: '2026-09-01T14:15:00Z',
  },
];

export const INITIAL_ISSUES = [
  {
    id: 'iss_001',
    user_id: 'usr_resident_001',
    reporter_name: 'Aarav Sharma',
    title: 'Severe Pothole Cluster near 5th Cross Junction',
    category: 'Roads & Potholes',
    description: 'Deep road cavity measuring approx 1.5m across causing severe traffic obstruction and two-wheeler skid hazards, especially during nighttime rainfall.',
    location: '5th Cross Rd, Green Valley Layout, Ward 14',
    latitude: 12.971598,
    longitude: 77.594562,
    severity: 'High',
    status: 'Resolved',
    reported_image_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    resolution_image_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    resolution_note: 'Asphalt cold-mix patched and steam-rolled by Municipal Road Maintenance Crew #4. Surface leveled and inspected for water drainage clearance.',
    priority_score: 85,
    created_at: '2026-09-18T08:30:00Z',
    resolved_at: '2026-09-22T16:45:00Z',
  },
  {
    id: 'iss_002',
    user_id: 'usr_resident_002',
    reporter_name: 'Priya Patel',
    title: 'Faulty High-Mast Streetlight creating Dark Zone',
    category: 'Street Lighting',
    description: 'Streetlight pole #SL-104 has been flickering and non-operational for over 4 days. Entire pedestrian walkway behind public park is completely pitch dark.',
    location: 'Opposite Community Park Gate 2, Rosewood Avenue',
    latitude: 12.975420,
    longitude: 77.599820,
    severity: 'Medium',
    status: 'Resolved',
    reported_image_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    resolution_image_url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    resolution_note: 'Damaged luminaire fuse and LED driver replaced with 90W energy-efficient fixture. Verified illumination coverage at 45 lux.',
    priority_score: 65,
    created_at: '2026-09-20T19:15:00Z',
    resolved_at: '2026-09-24T11:20:00Z',
  },
  {
    id: 'iss_003',
    user_id: 'usr_resident_001',
    reporter_name: 'Aarav Sharma',
    title: 'Municipal Pipeline Leakage flooding pedestrian pavement',
    category: 'Water & Leakage',
    description: 'Clean drinking water main line joint ruptured, wasting substantial gallons hourly and flooding the pedestrian walkway adjacent to the primary school.',
    location: 'Near St. Jude Elementary, 8th Main Road',
    latitude: 12.968210,
    longitude: 77.589410,
    severity: 'High',
    status: 'In Progress',
    reported_image_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    resolution_image_url: null,
    resolution_note: null,
    priority_score: 92,
    created_at: '2026-09-27T07:45:00Z',
    resolved_at: null,
  },
  {
    id: 'iss_004',
    user_id: 'usr_resident_002',
    reporter_name: 'Priya Patel',
    title: 'Solid Waste & Plastic Dumping on Vacant Plot',
    category: 'Waste & Garbage',
    description: 'Accumulated unattended domestic garbage pile attracting stray animals and creating foul odor near the residential block entrance.',
    location: 'Corner Plot 42, Sunrise Enclave, Sector 3',
    latitude: 12.978930,
    longitude: 77.604120,
    severity: 'Medium',
    status: 'Pending',
    reported_image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    resolution_image_url: null,
    resolution_note: null,
    priority_score: 68,
    created_at: '2026-09-29T10:10:00Z',
    resolved_at: null,
  },
  {
    id: 'iss_005',
    user_id: 'usr_resident_001',
    reporter_name: 'Aarav Sharma',
    title: 'Blocked Stormwater Drain causing Backflow Overflow',
    category: 'Drainage',
    description: 'Silt and debris choke in the concrete storm drain leading to stagnant water accumulation and mosquito breeding risk.',
    location: 'Behind Market Complex, 2nd Cross Drain Canal',
    latitude: 12.964500,
    longitude: 77.592300,
    severity: 'High',
    status: 'Pending',
    reported_image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    resolution_image_url: null,
    resolution_note: null,
    priority_score: 88,
    created_at: '2026-09-30T06:00:00Z',
    resolved_at: null,
  },
];
